[bar]
order = [ "default", "Bottom" ]

    [bar.Bottom]
    background_opacity = 0.84999998100101948
    capsule_radius = 3
    center = []
    concave_edge_corners = false
    enabled = true
    end = [ "cpu", "ram" ]
    margin_ends = 0
    position = "bottom"
    radius = 0
    shadow = false
    start = [ "taskbar" ]

        [bar.Bottom.monitor.HDMI-A-1]
        enabled = false

    [bar.default]
    background_opacity = 0.84999998100101948
    capsule_radius = 3
    center = [ "Media", "recorder" ]
    end = [ "tray", "notifications", "clipboard", "volume", "brightness", "battery", "clock" ]
    margin_edge = 0
    margin_ends = 0
    radius = 0
    shadow = false
    start = [ "launcher", "workspaces" ]

        [bar.default.monitor.HDMI-A-1]
        enabled = false

        [[bar.default.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "notifications", "clipboard", "volume", "brightness", "battery", "clock" ]
        opacity = 1.0
        padding = 6.0

[brightness]
enable_ddcutil = true

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
auto_hide = true
enabled = false
reserve_space = false

[idle]
pre_action_fade_seconds = 0

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1", "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 957.0
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 720.0
    cy = 777.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

[osd.kinds]
media = false

[plugins]
enabled = [ "noctalia/screen_recorder" ]

[shell]
avatar_path = "/home/zeon/Pictures/Wallpaper/photoahkana.png"
corner_radius_scale = 0.2500000037252903
font_family = "Roboto"
password_style = "random"
polkit_agent = true
time_format = "%-I:%M %p"

    [shell.animation]
    enabled = false

    [shell.panel]
    control_center_placement = "floating"
    open_near_click_control_center = true
    shadow = false
    transparency_mode = "soft"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 10.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 10.0
    enabled = true
    label = "Suspend"
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 10.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 10.0
    enabled = true
    shortcut = "4"
    variant = "destructive"

[theme]
custom_palette = "MyPalette"
source = "custom"

[wallpaper]
directory = "/home/zeon/Pictures/Wallpaper"

    [wallpaper.default]
    path = "/home/zeon/Pictures/Wallpaper/ahkanaa.png"

    [wallpaper.last]
    path = "/home/zeon/Pictures/Wallpaper/ahkanaa.png"

    [wallpaper.monitors.DP-1]
    path = "/home/zeon/Pictures/Wallpaper/ahkanaa.png"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/zeon/Pictures/Wallpaper/ahkanaa.png"

[widget.Media]
capsule = true
capsule_fill = "on_secondary"
capsule_padding = 12
command = "noctalia msg panel-toggle control-center media"
glyph = "music"
type = "custom_button"

[widget.audio_visualizer]
bands = 50
color_1 = "secondary"
width = 255.0

[widget.battery]
device = "/org/freedesktop/UPower/devices/battery_ps_controller_battery_a4oaeo12ob0o55o26"

[widget.cat]
audio_spectrum = true
tappy_mode = true
type = "noctalia/bongocat:cat"

[widget.clock]
format = "%-I:%M %p"

[widget.media]
album_art_only = true
max_length = 800
title_scroll = "on_hover"

[widget.recorder]
capsule = true
capsule_fill = "on_secondary"
capsule_padding = 12
type = "noctalia/screen_recorder:recorder"

[widget.sysmon]
stat = "ram_used"

[widget.taskbar]
pinned = [ "nemo" ]
show_all_outputs = true
show_window_title = true
workspace_group_capsule = false

[widget.workspaces]
capsule = true
display = "name"
max_label_chars = 10
occupied_color = "on_primary"
style = "minimal"
